SpottedBundle\Entity\Post:
  type: entity
  table: post
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
      content:
          column: name
          type: string
          nullable: false
          length: 255
      createdAt:
          column: created_at
          type: datetime
          nullable: false
  manyToOne:
      wall:
           targetEntity: Wall
           inversedBy: post
           joinColumn:
              name: wall_id
              referencedColumnName: id
              nullable: true

  lifecycleCallbacks: {  }
