imports:
    - { resource: parameters.yml }

framework:
    secret: '%secret_key%'
    form: ~
    assets: ~
    templating:
        engines: ['twig']
    serializer:
        enabled: true
        enable_annotations: true

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

jms_serializer:
    metadata:
        auto_detection: true

fos_rest:
    param_fetcher_listener: true
    service:
        serializer: jms_serializer.serializer
    serializer:
        serialize_null: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: 'force'
        serialize_null: true
        formats:
            json: true
            xml:  true

hautelook_alice:
    db_drivers:
        orm: ~
    locale: pl_PL
    seed: 1
    persist_once: true
    loading_limit: 5

nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600